services:
  - type: web
    name: ecommerce-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: secret123

  - type: static
    name: ecommerce-frontend
    buildCommand: cd frontend && npm install && CI=false npm run build
    publishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ecommerce-backend.onrender.com